# Reading in the Data

In [1]:
import csv as csv
import numpy as np
import pandas as pd


df = pd.read_csv('csv/train.csv',header=0)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# Identifying columns that aren't Float type or with NaN's

In [2]:
for col in df:
    if (df[col].dtypes != "float64"):
        print col, df[col].dtypes
    if ((len(df[df[col].isnull() == True])) > 0):
        print col, "Contains NaN's"

PassengerId int64
Survived int64
Pclass int64
Name object
Sex object
Age Contains NaN's
SibSp int64
Parch int64
Ticket object
Cabin object
Cabin Contains NaN's
Embarked object
Embarked Contains NaN's


# Dealing with NaN's in Age

I will replace the NaN's in Age with the median age of each passenger based off their respective gender and class.

In [3]:
median_ages = np.zeros((2,3))
median_ages

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Map passenger's gender to 0 or 1 in order to map gender and class later on.

In [4]:
df['Sex'] = df['Sex'].map({'female':0, 'male':1}).astype(int)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

Calculate median age by gender and class.

In [5]:
for i in range(0,2):
    for j in range(0,3):
        median_ages[i,j] = df[(df['Sex'] == i) & \
                              (df['Pclass'] == j+1)]['Age'].dropna().median()
median_ages

array([[ 35. ,  28. ,  21.5],
       [ 40. ,  30. ,  25. ]])

Replace NaN's with median age for passenger's gender and class

In [6]:
for i in range(0,2):
    for j in range(0,3):
        df.loc[(df.Age.isnull()) & (df.Sex == i) & (df.Pclass == j+1), \
                'Age'] = median_ages[i,j]
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

Confirm Age column is no longer empty

In [7]:
# Checks for empty columns in df
for column in df:
    if (len(df[df[column].isnull() == True])) > 0:
        print column

Cabin
Embarked


# Converting int64 col's to float

In [8]:
for col in df:
    if (df[col].dtypes == "int64"):
        df[col] = df[col].astype(float)

Confirm int's are converted.

In [9]:
for col in df:
    if (df[col].dtypes != "float64"):
        print col, df[col].dtypes
    if ((len(df[df[col].isnull() == True])) > 0):
        print col, "Contains NaN's"

Name object
Ticket object
Cabin object
Cabin Contains NaN's
Embarked object
Embarked Contains NaN's


In [10]:
df.head()

PassengerId  Survived  Pclass  \
0          1.0       0.0     3.0   
1          2.0       1.0     1.0   
2          3.0       1.0     3.0   
3          4.0       1.0     1.0   
4          5.0       0.0     3.0   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  1.0  22.0    1.0    0.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  0.0  38.0    1.0    0.0   
2                             Heikkinen, Miss. Laina  0.0  26.0    0.0    0.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  0.0  35.0    1.0    0.0   
4                           Allen, Mr. William Henry  1.0  35.0    0.0    0.0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

# Converting object col's to float

### Name

In [11]:
# Name: Nothing to do with name and can't be converted.
df = df.drop('Name',axis=1)
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch            Ticket  \
0          1.0       0.0     3.0  1.0  22.0    1.0    0.0         A/5 21171   
1          2.0       1.0     1.0  0.0  38.0    1.0    0.0          PC 17599   
2          3.0       1.0     3.0  0.0  26.0    0.0    0.0  STON/O2. 3101282   
3          4.0       1.0     1.0  0.0  35.0    1.0    0.0            113803   
4          5.0       0.0     3.0  1.0  35.0    0.0    0.0            373450   

      Fare Cabin Embarked  
0   7.2500   NaN        S  
1  71.2833   C85        C  
2   7.9250   NaN        S  
3  53.1000  C123        S  
4   8.0500   NaN        S

### Embarked

In [12]:
# Embarked: Only three ports, so map to 0 1 2.
df['Embarked'] = df['Embarked'].map({'S':0, 'C':1, 'Q':2}).astype(float)
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch            Ticket  \
0          1.0       0.0     3.0  1.0  22.0    1.0    0.0         A/5 21171   
1          2.0       1.0     1.0  0.0  38.0    1.0    0.0          PC 17599   
2          3.0       1.0     3.0  0.0  26.0    0.0    0.0  STON/O2. 3101282   
3          4.0       1.0     1.0  0.0  35.0    1.0    0.0            113803   
4          5.0       0.0     3.0  1.0  35.0    0.0    0.0            373450   

      Fare Cabin  Embarked  
0   7.2500   NaN       0.0  
1  71.2833   C85       1.0  
2   7.9250   NaN       0.0  
3  53.1000  C123       0.0  
4   8.0500   NaN       0.0

In [13]:
median_embarked = np.zeros((2,3))
median_embarked

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
for i in range(0,2):
    for j in range(0,3):
        median_embarked[i,j] = df[(df['Sex'] == i) & \
                              (df['Pclass'] == j+1)]['Embarked'].dropna().mean()
median_embarked

array([[ 0.48913043,  0.14473684,  0.61805556],
       [ 0.36065574,  0.11111111,  0.34870317]])

In [15]:
# Take the average port embarked by passengers based on their class and sex
for i in range(0,2):
    for j in range(0,3):
        median_embarked[i,j] = round(median_embarked[i,j] * 3)
median_embarked        

array([[ 1.,  0.,  2.],
       [ 1.,  0.,  1.]])

In [16]:
for i in range(0,2):
    for j in range(0,3):
        df.loc[(df.Embarked.isnull()) & (df.Sex == i) & (df.Pclass == j+1), \
                'Embarked'] = median_embarked[i,j]

Confirm embarked is all float and no more NaN's.

In [17]:
for col in df:
    if (df[col].dtypes != "float64"):
        print col, df[col].dtypes
    if ((len(df[df[col].isnull() == True])) > 0):
        print col, "Contains NaN's"

Ticket object
Cabin object
Cabin Contains NaN's


### Ticket

In [18]:
import re
# Strip all the prefixes
df['Ticket'] = df['Ticket'].map(lambda x: (re.sub(".*? (.+)", "\\1", x)))

# Define function that returns 0 if it can't convert to type
def tryconvert(value, default, *types):
    for t in types:
        try:
            return t(value)
        except ValueError, TypeError:
            continue
    return default

df['Ticket'] = df['Ticket'].map(lambda x: tryconvert(x,0,float))

Confirm Ticket is a float.

In [19]:
for col in df:
    if (df[col].dtypes != "float64"):
        print col, df[col].dtypes
    if ((len(df[df[col].isnull() == True])) > 0):
        print col, "Contains NaN's"

Cabin object
Cabin Contains NaN's


### Cabin

In [20]:
# Drop cabin because not much can be done with it right now.
df = df.drop('Cabin', axis=1)

Confirm everything is a float

In [21]:
for col in df:
    if (df[col].dtypes != "float64"):
        print col, df[col].dtypes
    if ((len(df[df[col].isnull() == True])) > 0):
        print col, "Contains NaN's"

# Random Forests! Finally!

In [22]:
#df = df.drop('Ticket',axis=1)
df = df.drop('PassengerId', axis=1)

In [23]:
df

Survived  Pclass  Sex   Age  SibSp  Parch     Ticket      Fare  Embarked
0         0.0     3.0  1.0  22.0    1.0    0.0    21171.0    7.2500       0.0
1         1.0     1.0  0.0  38.0    1.0    0.0    17599.0   71.2833       1.0
2         1.0     3.0  0.0  26.0    0.0    0.0  3101282.0    7.9250       0.0
3         1.0     1.0  0.0  35.0    1.0    0.0   113803.0   53.1000       0.0
4         0.0     3.0  1.0  35.0    0.0    0.0   373450.0    8.0500       0.0
5         0.0     3.0  1.0  25.0    0.0    0.0   330877.0    8.4583       2.0
6         0.0     1.0  1.0  54.0    0.0    0.0    17463.0   51.8625       0.0
7         0.0     3.0  1.0   2.0    3.0    1.0   349909.0   21.0750       0.0
8         1.0     3.0  0.0  27.0    0.0    2.0   347742.0   11.1333       0.0
9         1.0     2.0  0.0  14.0    1.0    0.0   237736.0   30.0708       1.0
10        1.0     3.0  0.0   4.0    1.0    1.0     9549.0   16.7000       0.0
11        1.0     1.0  0.0  58.0    0.0    0.0   113783.0   26.5500       0.0
12        0.0     3.0  1.0  20.0    0.0    0.0     2151.0    8.0500       0.0
13        0.0     3.0  1.0  39.0    1.0    5.0   347082.0   31.2750       0.0
14        0.0     3.0  0.0  14.0    0.0    0.0   350406.0    7.8542       0.0
15        1.0     2.0  0.0  55.0    0.0    0.0   248706.0   16.0000       0.0
16        0.0     3.0  1.0   2.0    4.0    1.0   382652.0   29.1250       2.0
17        1.0     2.0  1.0  30.0    0.0    0.0   244373.0   13.0000       0.0
18        0.0     3.0  0.0  31.0    1.0    0.0   345763.0   18.0000       0.0
19        1.0     3.0  0.0  21.5    0.0    0.0     2649.0    7.2250       1.0
20        0.0     2.0  1.0  35.0    0.0    0.0   239865.0   26.0000       0.0
21        1.0     2.0  1.0  34.0    0.0    0.0   248698.0   13.0000       0.0
22        1.0     3.0  0.0  15.0    0.0    0.0   330923.0    8.0292       2.0
23        1.0     1.0  1.0  28.0    0.0    0.0   113788.0   35.5000       0.0
24        0.0     3.0  0.0   8.0    3.0    1.0   349909.0   21.0750       0.0
25        1.0     3.0  0.0  38.0    1.0    5.0   347077.0   31.3875       0.0
26        0.0     3.0  1.0  25.0    0.0    0.0     2631.0    7.2250       1.0
27        0.0     1.0  1.0  19.0    3.0    2.0    19950.0  263.0000       0.0
28        1.0     3.0  0.0  21.5    0.0    0.0   330959.0    7.8792       2.0
29        0.0     3.0  1.0  25.0    0.0    0.0   349216.0    7.8958       0.0
..        ...     ...  ...   ...    ...    ...        ...       ...       ...
861       0.0     2.0  1.0  21.0    1.0    0.0    28134.0   11.5000       0.0
862       1.0     1.0  0.0  48.0    0.0    0.0    17466.0   25.9292       0.0
863       0.0     3.0  0.0  21.5    8.0    2.0     2343.0   69.5500       0.0
864       0.0     2.0  1.0  24.0    0.0    0.0   233866.0   13.0000       0.0
865       1.0     2.0  0.0  42.0    0.0    0.0   236852.0   13.0000       0.0
866       1.0     2.0  0.0  27.0    1.0    0.0     2149.0   13.8583       1.0
867       0.0     1.0  1.0  31.0    0.0    0.0    17590.0   50.4958       0.0
868       0.0     3.0  1.0  25.0    0.0    0.0   345777.0    9.5000       0.0
869       1.0     3.0  1.0   4.0    1.0    1.0   347742.0   11.1333       0.0
870       0.0     3.0  1.0  26.0    0.0    0.0   349248.0    7.8958       0.0
871       1.0     1.0  0.0  47.0    1.0    1.0    11751.0   52.5542       0.0
872       0.0     1.0  1.0  33.0    0.0    0.0      695.0    5.0000       0.0
873       0.0     3.0  1.0  47.0    0.0    0.0   345765.0    9.0000       0.0
874       1.0     2.0  0.0  28.0    1.0    0.0     3381.0   24.0000       1.0
875       1.0     3.0  0.0  15.0    0.0    0.0     2667.0    7.2250       1.0
876       0.0     3.0  1.0  20.0    0.0    0.0     7534.0    9.8458       0.0
877       0.0     3.0  1.0  19.0    0.0    0.0   349212.0    7.8958       0.0
878       0.0     3.0  1.0  25.0    0.0    0.0   349217.0    7.8958       0.0
879       1.0     1.0  0.0  56.0    0.0    1.0    11767.0   83.1583       1.0
880       1.0     2.0  0.0 

In [ ]:
df = pd.read_csv('csv/train.csv',header=0)
df.head()